/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package memory_game.Panel;

import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.event.*;



/**
 *
 * @author Gungai
 */
public class Alert extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form alert
     */
    public Alert() {
        initComponents();
        extiBtn.addActionListener(this);
        restartBtn.addActionListener(this);
        setVisible(true);
        setSize(400,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        score = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        restartBtn = new javax.swing.JButton();
        extiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(200, 100));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        score.setText("jLabel1");
        jPanel1.add(score);

        getContentPane().add(jPanel1);

        restartBtn.setText("Restart");
        jPanel2.add(restartBtn);

        extiBtn.setText("Exit to main menu");
        extiBtn.setActionCommand("Tomenu");
        jPanel2.add(extiBtn);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton extiBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton restartBtn;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables

    public JLabel getScoreLabel() {
        return score;
    }

    public void setScoreLabel(JLabel score) {
        this.score = score;
    }

    public JButton getExtiBtn() {
        return extiBtn;
    }

    public void setExtiBtn(JButton extiBtn) {
        this.extiBtn = extiBtn;
    }

    public JButton getRestartBtn() {
        return restartBtn;
    }

    public void setRestartBtn(JButton restartBtn) {
        this.restartBtn = restartBtn;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(restartBtn) || e.getSource().equals(extiBtn)){
            this.dispose();
            
        }
    }

}
